import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

export function TermsOfServicePage() {
  return (
    <main className="flex-grow flex flex-col items-center p-4">
      <div className="w-full max-w-4xl">
        <Card className="bg-white/50 dark:bg-gray-900/50 rounded-2xl shadow-xl">
          <CardHeader>
            <CardTitle className="text-3xl font-bold text-gray-800 dark:text-gray-100 text-center">
              Terms of Service
            </CardTitle>
          </CardHeader>
          <CardContent className="prose dark:prose-invert max-w-none text-left">
            <p className="text-sm text-gray-500 dark:text-gray-400 mb-6">
              Last updated: November 16, 2025
            </p>

            <h2>1. Acceptance of Terms</h2>
            <p>
              By accessing and using AI Blogify ("the Service"), you accept and agree to be bound by the terms
              and provision of this agreement.
            </p>

            <h2>2. Description of Service</h2>
            <p>
              AI Blogify is a web application that allows users to transform YouTube video transcripts into
              blog posts using Google's Gemini AI service. Users must provide their own Gemini AI API keys.
            </p>

            <h2>3. User Responsibilities</h2>
            <ul>
              <li>You must provide a valid Gemini AI API key obtained from Google</li>
              <li>You must comply with Google's Terms of Service for Gemini AI</li>
              <li>You are responsible for the content you generate and publish</li>
              <li>You must only use content you are authorized to work with</li>
            </ul>

            <h2>4. Content Usage and Copyright</h2>
            <h3>YouTube Content</h3>
            <p>
              The Service fetches publicly available transcripts from YouTube videos. By using this service:
            </p>
            <ul>
              <li>You acknowledge that transcript availability depends on video creator settings</li>
              <li>You agree to only transform content you're authorized to use</li>
              <li>You understand this is transformative fair use under copyright law</li>
              <li>You accept responsibility for any copyright violations in your usage</li>
            </ul>

            <h3>AI-Generated Content</h3>
            <p>
              Content generated by Gemini AI:
            </p>
            <ul>
              <li>Should be clearly marked as AI-generated</li>
              <li>May require fact-checking for accuracy</li>
              <li>Should not be presented as original human-created work without disclosure</li>
            </ul>

            <h2>5. Gemini AI Usage</h2>
            <p>
              By using this service, you agree to:
            </p>
            <ul>
              <li>Use only valid Gemini AI API keys you own or are authorized to use</li>
              <li>Comply with Google's Gemini AI Terms of Service</li>
              <li>Not exceed API rate limits or quotas</li>
              <li>Accept responsibility for all API usage costs</li>
            </ul>

            <h2>6. Prohibited Uses</h2>
            <p>You agree not to use the Service to:</p>
            <ul>
              <li>Generate harmful, offensive, or illegal content</li>
              <li>Violate any applicable laws or regulations</li>
              <li>Infringe on intellectual property rights</li>
              <li>Distribute copyrighted material without permission</li>
              <li>Spam or abuse the platform</li>
            </ul>

            <h2>7. Limitation of Liability</h2>
            <p>
              The Service is provided "as is" without warranties. We are not responsible for:
            </p>
            <ul>
              <li>Accuracy of AI-generated content</li>
              <li>Availability of YouTube transcripts</li>
              <li>API service disruptions</li>
              <li>Legal issues arising from user content</li>
            </ul>

            <h2>8. Privacy</h2>
            <p>
              Your API keys are stored locally in your browser and never transmitted to our servers
              except for direct API calls to Google's services. See our Privacy Policy for details.
            </p>

            <h2>9. Changes to Terms</h2>
            <p>
              We reserve the right to modify these terms at any time. Continued use of the service
              constitutes acceptance of updated terms.
            </p>

            <h2>10. Contact</h2>
            <p>
              If you have questions about these Terms of Service, please contact us through the application.
            </p>

            <div className="mt-8 p-4 bg-yellow-50 dark:bg-yellow-900/20 rounded-lg">
              <h3 className="font-semibold text-yellow-800 dark:text-yellow-200">Important Legal Notice</h3>
              <p className="text-sm text-yellow-700 dark:text-yellow-300">
                This service is provided for educational and creative purposes. Users are responsible for
                ensuring their use complies with applicable laws, including copyright and fair use regulations.
                We recommend consulting legal counsel for specific use cases involving copyrighted material.
              </p>
            </div>
          </CardContent>
        </Card>
      </div>
    </main>
  );
}
